# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    # Most of these are dependencies of puppetlabs/ssh.
    acl: 'puppetlabs/acl'
    bash: 'ploperations/bash'
    chocolatey: 'puppetlabs/chocolatey'
    classification: 'ploperations/classification'
    concat: 'puppetlabs/concat'
    cygwin: 'mdelaney/cygwin'
    node_encrypt: 'binford2k/node_encrypt'
    registry: 'puppetlabs/registry'
    ssh: 'ploperations/ssh'
    windows_env: 'puppet/windows_env'
    sshkeys_core: 'puppetlabs/sshkeys_core'
    stdlib: 'puppetlabs/stdlib'
    zsh: 'ploperations/zsh'
